# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BookInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, author: str=None, published_year: int=None):  # noqa: E501
        """BookInput - a model defined in Swagger

        :param title: The title of this BookInput.  # noqa: E501
        :type title: str
        :param author: The author of this BookInput.  # noqa: E501
        :type author: str
        :param published_year: The published_year of this BookInput.  # noqa: E501
        :type published_year: int
        """
        self.swagger_types = {
            'title': str,
            'author': str,
            'published_year': int
        }

        self.attribute_map = {
            'title': 'title',
            'author': 'author',
            'published_year': 'publishedYear'
        }
        self._title = title
        self._author = author
        self._published_year = published_year

    @classmethod
    def from_dict(cls, dikt) -> 'BookInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookInput of this BookInput.  # noqa: E501
        :rtype: BookInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this BookInput.


        :return: The title of this BookInput.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this BookInput.


        :param title: The title of this BookInput.
        :type title: str
        """

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this BookInput.


        :return: The author of this BookInput.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this BookInput.


        :param author: The author of this BookInput.
        :type author: str
        """

        self._author = author

    @property
    def published_year(self) -> int:
        """Gets the published_year of this BookInput.


        :return: The published_year of this BookInput.
        :rtype: int
        """
        return self._published_year

    @published_year.setter
    def published_year(self, published_year: int):
        """Sets the published_year of this BookInput.


        :param published_year: The published_year of this BookInput.
        :type published_year: int
        """

        self._published_year = published_year
